# Typing stub for signal_protocol.address module
# Direct class definition instead of type alias

from ._signal_protocol.address import ProtocolAddress as _ProtocolAddressImpl

class ProtocolAddress(_ProtocolAddressImpl):
    """An address identifying a Signal Protocol participant."""

    def __init__(self, name: str, device_id: int) -> None: ...
    def name(self) -> str: ...
    def device_id(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

__all__ = ["ProtocolAddress"]
