name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: |
        pip install mypy pytest

    - name: Build wheel
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release --out dist

    - name: Install wheel linux
      if: runner.os != 'Windows'
      run: |
        pip install dist/*.whl

    - name: Install wheel (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $wheel = Get-ChildItem -Path "dist" -Filter "*.whl" | Select-Object -First 1
        pip install $wheel.FullName --force-reinstall


    - name: Run pytest
      run: |
        python -m pytest tests/ -v

    - name: Verify manual stub file exists
      run: |
        # Check that the manually created stub file is present in the installed package
        python -c "
        import signal_protocol
        import os
        print('Package location:', signal_protocol.__file__)
        pyi_file = os.path.join(os.path.dirname(signal_protocol.__file__), '_signal_protocol.pyi')
        print('Stub file exists:', os.path.exists(pyi_file))
        "

    - name: Validate type stubs with mypy
      run: |
        # Type check the stub file itself
        python -c "
        import signal_protocol
        import os
        pyi_file = os.path.join(os.path.dirname(signal_protocol.__file__), '_signal_protocol.pyi')
        print('Type checking:', pyi_file)
        "
        python -m mypy --python-executable python -c "import signal_protocol" --ignore-missing-imports
        echo "Type stub validation successful"

    - name: Type check test files (optional)
      run: |
        # Optional: Type check your test files to ensure stubs work properly
        python -m mypy tests/ --ignore-missing-imports || true
        echo "Test type checking completed (non-blocking)"
