name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR creation, updates, and reopening

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build wheel
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release --out dist

    - name: Install package and test dependencies
      run: |
        pip install dist/*.whl
        pip install mypy pytest

    - name: Isolate installed package for testing
      run: |
        echo "Moving signal_protocol source directory to avoid import conflict"
        mv signal_protocol signal_protocol_source_tmp
        echo "Contents of workspace after move:"
        ls -la

    - name: Run pytest
      id: pytest_run # Added id here
      run: pytest -v signal_protocol_source_tmp/tests
      # Continue on error to ensure cleanup step runs
      continue-on-error: true

    - name: Check pytest exit code
      run: |
        if [ "${{ steps.pytest_run.outcome }}" == "failure" ]; then
          echo "Pytest failed"
          exit 1
        fi

    - name: Restore source directory
      # Always run this step to ensure cleanup, even if pytest failed
      if: always()
      run: |
        echo "Restoring signal_protocol source directory"
        mv signal_protocol_source_tmp signal_protocol
        echo "Contents of workspace after restore:"
        ls -la

    - name: Verify manual stub file exists
      run: |
        # Check that the manually created stub file is present
        ls -la signal_protocol/_signal_protocol.pyi
        echo "Manual stub file found and will be used for type checking"

    - name: Validate type stubs with mypy
      run: |
        # Type check the stub file itself
        python -m mypy signal_protocol/_signal_protocol.pyi --ignore-missing-imports
        echo "Type stub validation successful"

    - name: Type check test files (optional)
      run: |
        # Optional: Type check your test files to ensure stubs work properly
        python -m mypy tests/ --ignore-missing-imports || true
        echo "Test type checking completed (non-blocking)"
