name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build wheel
      uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release --out dist

    - name: Install package and test dependencies
      run: |
        pip install dist/*.whl
        pip install mypy pytest

    - name: Run pytest
      run: pytest -v

    - name: Verify manual stub file exists
      run: |
        # Check that the manually created stub file is present
        ls -la signal_protocol/_signal_protocol.pyi
        echo "Manual stub file found and will be used for type checking"

    - name: Validate type stubs with mypy
      run: |
        # Type check the stub file itself
        python -m mypy signal_protocol/_signal_protocol.pyi --ignore-missing-imports
        echo "Type stub validation successful"

    - name: Type check test files (optional)
      run: |
        # Optional: Type check your test files to ensure stubs work properly
        python -m mypy tests/ --ignore-missing-imports || true
        echo "Test type checking completed (non-blocking)"
