name: Python Tests

on:
  push:
    branches: [ main ] # Assuming 'main' is the primary branch
  pull_request:
    branches: [ main ] # Assuming 'main' is the primary branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9'] # Can be expanded, e.g., ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-11-09 # From rust-toolchain file
        override: true
        components: rustfmt, clippy # Optional, but good practice

    - name: Install Python build dependencies
      run: pip install -U setuptools wheel setuptools-rust

    - name: Build Rust extension
      run: python setup.py build_ext --inplace

    - name: Run Python tests
      run: python -m unittest discover tests
